### ISSUE TITLE
DefaultEncoding should be UTF-8

### ISSUE THREAD

**Issue by hiro0107** [scaruby/scaruby#9]
This module uses a value of `System.getProperty("file.encoding")` as the default encoding. ([Source](https://github.com/scaruby/scaruby/blob/master/src/main/scala/com/github/scaruby/package.scala))
In recent days, many developers use UTF-8 as a default encoding, but rarely uses `System.getProperty("file.encoding")`.

So, could you change the value to UTF-8?

**Comment by kmizu** [comment]
Hi, @hiro0107 .  I'm sorry for too late reply.  As you said, since I think many developers use UTF-8 as a default encoding, I'll change the default value to UTF-8 in scaruby 0.4.

**Comment by kmizu** [comment]
Oops!  I'd already changed the default encoding to UTF-8 ([Source](https://github.com/scaruby/scaruby/blob/d77961f236df6cb07720f98a1cc870740983c701/src/main/scala/com/github/scaruby/package.scala#L11)).  Then, this issue will be closed.
